### ISSUE TITLE
Move proxy/roslaunch into ros1 module and rename to ROS1...

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/roswire#407]

**Comment by schmerl** [comment]
In order to support different versions of ROS, the code in proxy/roslaunch should be abstracted into interfaces, and the implementation code should be moved into a ros1 module similar to the existing ros2. These classes should be "abstracted":

- _ROSLaunchController_: Manages a launch process
- _LaunchFileReader_: Reads and processes launch files into internal data structures (partially done)
- _ROSLaunchManager_: Provides access to reading, writing, and running launch files
